# Autogenerated wrapper script for Intel_XED_jll for x86_64-unknown-freebsd
export libxed, libxed_ild

JLLWrappers.@generate_wrapper_header("Intel_XED")
JLLWrappers.@declare_library_product(libxed, "libxed.so")
JLLWrappers.@declare_library_product(libxed_ild, "libxed-ild.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libxed,
        "lib/libxed.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxed_ild,
        "lib/libxed-ild.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
